apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: cloud-native-applications
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: "uuhnaut69/store-api"
      context: store-api
      sync:
        infer:
          - "**/*"

manifests:
  rawYaml:
    - k8s/*.yaml

deploy:
  kubectl: {}
  helm:
    releases:
      - name: postgresql
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - helm/postgresql/values.yaml
        wait: true

      - name: store-api
        chartPath: helm/store-api
        valuesFiles:
          - helm/store-api/values.yaml
        version: 0.1.0
