architecture: "standalone"

global:
  postgresql:
    auth:
      existingSecret: "postgresql-secret"
      secretKeys:
        adminPasswordKey: "postgresql-password"
        userPasswordKey: "postgresql-password"
